server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.130:8848
        # 在nacos中新增命名空间, 将命名空间的id复制过来
        namespace: 2bd390ac-1a7d-44f9-8bf8-dcf7b5694827

    gateway:
      # 开启网关的跨域功能，具体微服务上的跨域需要进行关闭，否则无效
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddRequestHeader=source, pai-api-gateway

      routes:
        - id: api-admin
          uri: lb://api-admin
          predicates:
            - Path=/api/admin/**

        - id: api-itf
          uri: lb://api-itf
          predicates:
            - Path=/api/itf/**
          filters:
            - name: RequestRateLimiter
              args:
                #令牌桶每秒的填充速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶的容量
                redis-rate-limiter.burstCapacity: 2
                #用什么做为key (写配置类的方法名)
                key-resolver: "#{@ipKeyResolver}"

  redis:
    host: 192.168.79.130
    port: 6379
    password: root     #密码
    database: 15
    timeout: 10000    #访问超时时间
    lettuce: #lettuce依赖commons-pool2, 所以要导入commons-pool2
      pool:
        max-active: 10  #连接池最大连接数  
        max-wait: 5000  #连接池最大等待阻塞时间
        max-idle: 10     #连接池中最大空闲连接数
        min-idle: 2     #连接池中最小空闲数

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: PanAPIToken
  # token 永久有效期, 7天(604800秒)后，token必定过期，无法继续使用
  timeout: 604800
  # token 最低活跃频率, 超过30分钟(1800秒)没有请求, token过期
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志 
  is-log: true