server:
  port: 9998
  servlet:
    context-path: /api/itf

spring:
  application:
    name: api-itf

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.130:8848
        # 在nacos中新增命名空间, 将命名空间的id复制过来
        namespace: 2bd390ac-1a7d-44f9-8bf8-dcf7b5694827
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_api
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.79.130
    port: 6379
    password: root     #密码
    database: 0
    timeout: 10000    #访问超时时间
    lettuce: #lettuce依赖commons-pool2, 所以要导入commons-pool2
      pool:
        max-active: 10  #连接池最大连接数  
        max-wait: 5000  #连接池最大等待阻塞时间
        max-idle: 10     #连接池中最大空闲连接数
        min-idle: 2     #连接池中最小空闲数
  
  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区

management:
  endpoints:
    web:
      exposure:
        include: "*"

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(1-已删除 0-未删除)
