server:
  port: ${SERVER_PORT:9999}
  servlet:
    context-path: /api/admin

spring:
  application:
    name: api-admin

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        # 在nacos中新增命名空间, 将命名空间的id复制过来
        namespace: ${NACOS_NAMESPACE:2bd390ac-1a7d-44f9-8bf8-dcf7b5694827}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:open_api}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PWD:root}
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_POST:6379}
    password: ${REDIS_PWD:root}     #密码
    database: 15
    timeout: 10000    #访问超时时间
    lettuce: #lettuce依赖commons-pool2, 所以要导入commons-pool2
      pool:
        max-active: 10  #连接池最大连接数  
        max-wait: 5000  #连接池最大等待阻塞时间
        max-idle: 10     #连接池中最大空闲连接数
        min-idle: 2     #连接池中最小空闲数

  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(1-已删除 0-未删除)

# knife4j的增强配置
knife4j:
  enable: true
  # 开启生产环境屏蔽
  production: true
  setting:
    language: zh_cn
    # 是否启用Host
    enable-host: true
    # 启用Host后地址，例如：http://192.168.0.111:8080
    enable-host-text: http://localhost:8888

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: PanAPIToken
  # token 永久有效期, 7天(604800秒)后，token必定过期，无法继续使用
  timeout: 604800
  # token 最低活跃频率, 超过30分钟(1800秒)没有请求, token过期
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志 
  isl-og: true

pan-api:
  client:
    access-key: ${PAN_API_AK:admin}
    secret-key: ${PAN_API_SK:admin}